# Generated by Django 4.2.7 on 2023-11-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="cbresults", options={},),
    ]
